### PR TITLE
Create FedoraProject-MyanmarCommunity-api.json

### PR DESCRIPTION
**Pull request by orcakrilozona**
Adding Fedora Project - Myanmar Community

### CODE REVIEW

**Comment by samarjeet27** [comment]
Thank you @orcakrilozona, can you add this link to the (directory)[http://github.com/fossasia/directory.api.fossasia.net] ?

**Comment by orcakrilozona** [comment]
Thank you @samarjeet27 , I guess it's already there as far as I can see here https://github.com/fossasia/directory.api.fossasia.net/blob/master/directory.json :+1:

**Comment by samarjeet27** [comment]
@orcakrilozona, I mean add this link

https://raw.githubusercontent.com/fossasia/fossasia-communities/3ed715580509082626de157f8cfe5510d3be5bc7/Myanmar/FedoraProject-MyanmarCommunity-api.json

this makes it easier to manage and less risk of broken links

**Comment by orcakrilozona** [comment]
@samarjeet27 , got it. added. Thanks :+1:

**Comment by samarjeet27** [comment]
@orcakrilozona, sorry I gave a bad link it's working but links to your commit add the link above ^^

**Comment by orcakrilozona** [comment]
Thanks @samarjeet27 :D

**Pull request merged**
