### PR TITLE
Added Japan, India, and Hong Kong community

### PR DESCRIPTION
**Pull request by JamMurz**
Added Yokohama Linux User Group, and removed mozilla japan. Also added mozilla hong kong and mozilla Kerala. Task was https://www.google-melange.com/gci/task/view/google/gci2014/5326906169753600

### CODE REVIEW

**Comment by hpdang** [comment]
Hi, I cannot find the file for the Yoko-Lug.

**Comment by JamMurz** [comment]
@hpdang I'm pretty sure the yoko-lug file is in here, can you check again? Thanks

**Comment by JamMurz** [comment]
@hpdang Can you check this again I think the Yoko-lug file is in

**Comment by JamMurz** [comment]
@mariobehling can you check this?

**Pull request merged**
